### PR TITLE
restructure the repo

### PR DESCRIPTION
**Pull request by comus**
hello, @eric-burel,  this PR do several things

**you may want take a look first**
https://github.com/comus/vulcan-next-starter/tree/dev

1. add some eslint, "copy" from next.js repo
2. add packages folder temporarily
i think it would be easier to try those `@vulcan` lib in packages first.
because we can debug those code in the some repo, and not need to yarn link those npm modules
when the lib finish, we can just copy those code to vulcan-npm and npm publish it
see: https://github.com/comus/vulcan-next-starter/blob/dev/packages/%40vulcan/webpack/withVulcan.js#L40
```
config.resolve.modules = [
        ...(config.resolve.modules || []),
        path.join(__dirname, '..', '..', '..', 'packages'),
        'node_modules'
      ]
```
so we can just `import xxx from '@vulcan/yyy'`
3. use the helper function with the pages, withVulcan
it handle those apollo client things, copy from official nextjs apollo example
`import { withVulcan } from '@vulcan/core'`

4. webpack helper in next.config.js
```
const { withVulcan } = require('./packages/@vulcan/webpack')
```

p.s. i may accidentally removed some of your settings or comments. feel free to just copy some of my code if u think useful. my english is not very good.

i saw that you already write some code to connect existing meteor vulcan project

### CODE REVIEW

**Comment by eric-burel** [comment]
Awesome update! Yeah the `packages` thing is a great idea at least during early development, linking can be annoying. However just a question, shouldn't the `withVulcan` helper be used in `_app.js` instead so it's used systematically in pages? I'd like to Vulcan use to be as transparent as possible for the end user, so avoiding the need for a specific export in pages for example.

**Comment by eric-burel** [comment]
Also a more technical question but do you think we may be able to use Express instead of Micro? Micro have way less traction than other framework, and even if it's Zeit's choice I am a bit affraid to go for a server that is not either Express or Koa (we already had additional work in Meteor just because it uses a Connect server instead of Express...)

**Comment by comus** [comment]
> shouldn't the withVulcan helper be used in _app.js instead so it's used systematically in pages (Edit: I am talking about the one from @vulcan/core specifically) ?

yes, you are right, so basically withVulcan = the official withApollo helper function, it can use in every page or just _app.js

its ok if it just
```
import { AppProps } from 'next/app'
import { withVulcan } from '@vulcan/core'

const IS_PROD = process.env.NODE_ENV === 'production'

const graphqlUrl = IS_PROD
  ? process.env.GRAPHQL_URL
  : 'http://localhost:3001/graphql'

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default withVulcan({ ssr: true, graphqlUrl })(MyApp)
```
so where to place `withVulcan` is up to the developers

**Comment by comus** [comment]
> Also a more technical question but do you think we may be able to use Express instead of Micro?

actually my other projects use apollo-server-express too, haha

Although micro is smaller(size), express middleware is more convenient to use in some case

**Comment by comus** [comment]
so i think vulcan-npm those core modules can export some helper functions, and not UI relative.

it can use in many project such as CRA or Next.js

to extend webpack, to add apollo client, and easier and quickly to create vulcan apollo server

finally, /api/graphql.ts will change to something like that
```
export default createVulcanServer(...)
```

**Comment by eric-burel** [comment]
What do you mean by "so i think vulcan-npm those core modules can export some helper functions, and not UI relative."?
I expect our NPM package to have the same spirit as our Meteor packages, with both UI and server code in order to deliver features, I think that's really differentiating Vulcan from other projects. However of course come packages can be server only or client only where it makes sense.

**Comment by comus** [comment]
Oh. I see. Just think that if switch to next js or others. There are some other UI such as chakra or style-components those other ui framework. Currently Vulcan use bootstrap right? I don’t know. Above sentence I wrote just say that if the library not relative specific ui framework such as Formik. It would be more flexible.

**Comment by eric-burel** [comment]
Currently Vulcan is rather good on this point, we support Bootstrap, Material UI, and setting up Styled Components. Most of the difficulty comes from SSR (so even for UI you need both a server and a client export).
But yes you are right, we progressively improve Vulcan so each piece is more reusable and more independant from the other, so you can reuse Vulcan features, or swap some technical choice (Formik vs smth else etc.)

I am in the process of merging your PR, it's really great

**Comment by eric-burel** [comment]
Merged in the `devel` branch :tada:

**Pull request closed without merging**
